### ISSUE TITLE
Include payment information when processing orders

### ISSUE THREAD

**Issue by gtenaschuk** [DinkumInteractive/woocommerce-muse#21]
We need to include payment information in orders, currently it is empty

**Comment by Sean12mps** [comment]
What are the payment methods we should place here?
For each payment method, we might also need the required fields to send.

From what I know, vanilla WooCommerce don't have a credit card payment method.
I'm going to add braintree and stripe CC fields for now.

**Comment by Sean12mps** [comment]
Discussion is open here.
https://github.com/DinkumInteractive/woocommerce-muse/pull/28
